WIP:MySQL Directory Format
borgmatic-collective/borgmatic pull request #84
Opened 2024-08-08 11:45 UTC by shivansh02

Adds support for directory format for MySQL databases.

To Do:
- [ ] Write new/modify unit tests
- [ ] Modify E2E tests

2024-08-20 08:49 UTC, shivansh02 commented
To test the feature, I tried running `mysqldump` on a database but got the following error:
`The MySQL server is running with the --secure-file-priv option so it cannot execute this statement](https://stackoverflow.com/questions/74932524/mysql-error-code-1290-the-mysql-server-is-running-with-the-secure-file-priv)`

To fix that, I added the following lines to mysql config files:
```
[mysqld]
secure-file-priv = ""
```

Now, the error I'm getting is 
`unknown variable 'secure-file-priv='`
I removed the variable from all the config files I tried setting it in, the error still remains.
Tried to allow AppArmor according to this answer, but to no avail:
[https://stackoverflow.com/a/57502632/20831469](https://stackoverflow.com/a/57502632/20831469)

2024-08-20 22:51 UTC, witten commented
Maybe try `secure_file_priv` with underscores instead of dashes? Although [these docs](https://dev.mysql.com/doc/refman/8.4/en/server-system-variables.html#sysvar_secure_file_priv) say an empty value has "no effect" which is not reassuring. You could also try setting it to the actual directory that you'll be dumping to.

2024-08-20 23:39 UTC, witten reviewed
What do you think of making these changes to the MariaDB database hook as well, as it's pretty identical to the MySQL hook right now? The main difference is that the specific binaries it runs have different names.

2024-08-20 23:39 UTC, witten commented on borgmatic/hooks/mysql.py
> +    dump_format = database.get('format')
Style nit: This variable could easily inlined given that it's not used anywhere else besides the next line.

2024-08-20 23:39 UTC, witten commented on borgmatic/hooks/mysql.py
> +    else:
You could lose the `else:` given that the other code path returns early. (Do not feel strongly.)

2024-08-20 23:39 UTC, witten commented on borgmatic/hooks/mysql.py
> +                    (dump_name,),
I'm not quite following this changed and the earlier deletions. Don't you still need some of that logic if the database name is `all`?

2024-08-20 23:39 UTC, witten commented on borgmatic/hooks/mysql.py
> +    dump_format = data_source.get('format')
Similar here; could be inlined.

2024-08-20 23:39 UTC, witten commented on borgmatic/hooks/mysql.py
> +        )
I think I'm missing something.. These two commands look identical to me. Maybe it's just still WIP.

2024-08-20 23:46 UTC, witten commented on borgmatic/hooks/mysql.py
> +            if file.endswith('.sql'):
[The docs say]( https://dev.mysql.com/doc/refman/8.4/en/mysqldump.html#option_mysqldump_tab)these are `.txt` files...?

2024-08-21 13:56 UTC, shivansh02 commented
> What do you think of making these changes to the MariaDB database hook as well, as it's pretty identical to the MySQL hook right now? The main difference is that the specific binaries it runs have different names.

Yes I proposed making similar changes to MariaDB hook as well. I'll get on it as soon as I can get this PR approved, so it saves time.

2024-08-22 19:56 UTC, shivansh02 commented
I was able to fix the `--secure-file-priv` error, but when I run 
`sudo borgmatic --add-drop-database --databases DBName --result-file /root/.borgmatic/mysql_databases/localhost/DBName`,
I get the following error:
`Cant create/write to file /root/.borgmatic/mysql_databases/localhost/DBName (OS errno 20 - Not a directory).`
Am I missing something? I ran this command to debug why my DB dump was not present in my backups, even without the --tab option.

2024-08-24 08:45 UTC, shivansh02 commented
@witten I made changes that hopefully resolve all the issues above. Please take a look.

2024-08-29 18:03 UTC, witten requested changes
Finally got around to giving this a look. Thank you so much for your patience! I'll try to be a little faster on the next round.

2024-08-29 18:03 UTC, witten commented on borgmatic/hooks/mysql.py
> +                    execute_command_with_processes(
I don't think you want the `_with_processes()` variant for this use case. That's intended for passing in, say, an `extract_process` so as to extract a single file into a restore command via background streaming. But that's not what you're doing here; this is presumably a synchronous call (... it's not streaming from `borg extract`). So, for that, maybe try just `execute_command()`?

2024-11-08 23:26 UTC, witten commented
Do you still plan on working on this one? Thanks!

2025-01-27 22:37 UTC, witten commented
Closing due to inactivity, but I'd be happy to revisit if you're still game. Thanks!

2025-01-27 22:37 UTC, closed without merging